import type {
  AdjacentTopics,
  PlaywrightTopic,
  TopicGroupId,
  TopicLevel,
  TopicNavGrouped,
} from "./types"
import { EXCLUDED_PLAYWRIGHT_LEARN_CATALOG_SLUGS } from "./constants"
import { filterPlaywrightLearnTopicTsTest } from "./ts-playwright-stack-filter"
import { autoGeneratedPlaywrightTopics } from "./topics/auto"
import { chromeExtensionsTopic } from "./topics/chrome-extensions"
import { introTopic } from "./topics/intro"
import { runningTestsTopic } from "./topics/running-tests"
import { serviceWorkersTopic } from "./topics/service-workers"
import { writingTestsTopic } from "./topics/writing-tests"

const ALL: PlaywrightTopic[] = [
  introTopic,
  writingTestsTopic,
  runningTestsTopic,
  chromeExtensionsTopic,
  serviceWorkersTopic,
  ...autoGeneratedPlaywrightTopics,
]

const EXCLUDED_TOPIC_SLUGS = new Set<string>(
  EXCLUDED_PLAYWRIGHT_LEARN_CATALOG_SLUGS,
)

/** Sorted pedagogical order (lower `order` first). */
export const PLAYWRIGHT_TOPICS: PlaywrightTopic[] = [...ALL]
  .filter((t) => !EXCLUDED_TOPIC_SLUGS.has(t.slug))
  .sort((a, b) => a.order - b.order)

export function getAllSlugs(): string[] {
  return PLAYWRIGHT_TOPICS.map((t) => t.slug)
}

export function getTopicBySlug(slug: string): PlaywrightTopic | undefined {
  const raw = PLAYWRIGHT_TOPICS.find((t) => t.slug === slug)
  return raw ? filterPlaywrightLearnTopicTsTest(raw) : undefined
}

export type { AdjacentTopics } from "./types"

export function getAdjacentTopics(slug: string): AdjacentTopics {
  const i = PLAYWRIGHT_TOPICS.findIndex((t) => t.slug === slug)
  if (i === -1) return {}
  const slim = (t: PlaywrightTopic) => ({ slug: t.slug, title: t.title })
  return {
    prev: i > 0 ? slim(PLAYWRIGHT_TOPICS[i - 1]) : undefined,
    next:
      i < PLAYWRIGHT_TOPICS.length - 1
        ? slim(PLAYWRIGHT_TOPICS[i + 1])
        : undefined,
  }
}

export type GroupedTopics = {
  groupId: TopicGroupId
  topics: PlaywrightTopic[]
}[]

/** Topics grouped by their declared groupId, preserving overall order. */
export function getTopicsByGroup(): GroupedTopics {
  const result: GroupedTopics = []
  for (const topic of PLAYWRIGHT_TOPICS) {
    const bucket = result.find((g) => g.groupId === topic.groupId)
    if (bucket) {
      bucket.topics.push(topic)
    } else {
      result.push({ groupId: topic.groupId, topics: [topic] })
    }
  }
  return result
}

/** Slug + title only — safe to pass from server layouts to client nav. */
export function getTopicNavByGroup(): TopicNavGrouped {
  return getTopicsByGroup().map((g) => ({
    groupId: g.groupId,
    topics: g.topics.map((t) => ({ slug: t.slug, title: t.title })),
  }))
}

export const TRACK_META: Record<
  TopicLevel,
  {
    label: { en: string; uk: string }
    description: { en: string; uk: string }
    color: string
  }
> = {
  beginner: {
    label: { en: "Beginner", uk: "Початківець" },
    description: {
      en: "Install Playwright, write your first test, and master the core APIs.",
      uk: "Встановіть Playwright, напишіть перший тест і опануйте базові API.",
    },
    color: "#22c55e",
  },
  intermediate: {
    label: { en: "Intermediate", uk: "Середній рівень" },
    description: {
      en: "Master fixtures, network mocking, authentication, and multi-browser flows.",
      uk: "Освойте fixtures, мок мережі, автентифікацію та багатобраузерні сценарії.",
    },
    color: "#3b82f6",
  },
  advanced: {
    label: { en: "Advanced", uk: "Просунутий рівень" },
    description: {
      en: "Visual snapshots, CI pipelines, Docker, emulation, and framework integrations.",
      uk: "Візуальні снепшоти, CI пайплайни, Docker, емуляція та інтеграція з фреймворками.",
    },
    color: "#a855f7",
  },
}

/** Topics in a single learning track, sorted by trackOrder. */
export function getTopicsByLevel(level: TopicLevel): PlaywrightTopic[] {
  return PLAYWRIGHT_TOPICS.filter((t) => t.level === level).sort(
    (a, b) => a.trackOrder - b.trackOrder,
  )
}

/** Prev/next within the same level track. */
export function getAdjacentTopicsInTrack(slug: string): AdjacentTopics {
  const topic = PLAYWRIGHT_TOPICS.find((t) => t.slug === slug)
  if (!topic) return {}
  const track = getTopicsByLevel(topic.level)
  const i = track.findIndex((t) => t.slug === slug)
  if (i === -1) return {}
  const slim = (t: PlaywrightTopic) => ({ slug: t.slug, title: t.title })
  return {
    prev: i > 0 ? slim(track[i - 1]) : undefined,
    next: i < track.length - 1 ? slim(track[i + 1]) : undefined,
  }
}

const LEVEL_ORDER: TopicLevel[] = ["beginner", "intermediate", "advanced"]

/** Slug of the first topic in the next level track, or undefined if already advanced. */
export function getNextLevelFirstSlug(level: TopicLevel): string | undefined {
  const idx = LEVEL_ORDER.indexOf(level)
  const next = LEVEL_ORDER[idx + 1]
  return next ? getTopicsByLevel(next)[0]?.slug : undefined
}
