import type {
  AdjacentTopics,
  PlaywrightTopic,
  TopicGroupId,
  TopicNavGrouped,
} from "./types"
import { EXCLUDED_PLAYWRIGHT_LEARN_CATALOG_SLUGS } from "./constants"
import { filterPlaywrightLearnTopicTsTest } from "./ts-playwright-stack-filter"
import { autoGeneratedPlaywrightTopics } from "./topics/auto"
import { chromeExtensionsTopic } from "./topics/chrome-extensions"
import { introTopic } from "./topics/intro"
import { runningTestsTopic } from "./topics/running-tests"
import { serviceWorkersTopic } from "./topics/service-workers"
import { writingTestsTopic } from "./topics/writing-tests"

const ALL: PlaywrightTopic[] = [
  introTopic,
  writingTestsTopic,
  runningTestsTopic,
  chromeExtensionsTopic,
  serviceWorkersTopic,
  ...autoGeneratedPlaywrightTopics,
]

const EXCLUDED_TOPIC_SLUGS = new Set<string>(
  EXCLUDED_PLAYWRIGHT_LEARN_CATALOG_SLUGS,
)

/** Sorted pedagogical order (lower `order` first). */
export const PLAYWRIGHT_TOPICS: PlaywrightTopic[] = [...ALL]
  .filter((t) => !EXCLUDED_TOPIC_SLUGS.has(t.slug))
  .sort((a, b) => a.order - b.order)

export function getAllSlugs(): string[] {
  return PLAYWRIGHT_TOPICS.map((t) => t.slug)
}

export function getTopicBySlug(slug: string): PlaywrightTopic | undefined {
  const raw = PLAYWRIGHT_TOPICS.find((t) => t.slug === slug)
  return raw ? filterPlaywrightLearnTopicTsTest(raw) : undefined
}

export type { AdjacentTopics } from "./types"

export function getAdjacentTopics(slug: string): AdjacentTopics {
  const i = PLAYWRIGHT_TOPICS.findIndex((t) => t.slug === slug)
  if (i === -1) return {}
  const slim = (t: PlaywrightTopic) => ({ slug: t.slug, title: t.title })
  return {
    prev: i > 0 ? slim(PLAYWRIGHT_TOPICS[i - 1]) : undefined,
    next:
      i < PLAYWRIGHT_TOPICS.length - 1
        ? slim(PLAYWRIGHT_TOPICS[i + 1])
        : undefined,
  }
}

export type GroupedTopics = {
  groupId: TopicGroupId
  topics: PlaywrightTopic[]
}[]

/** Topics grouped by their declared groupId, preserving overall order. */
export function getTopicsByGroup(): GroupedTopics {
  const result: GroupedTopics = []
  for (const topic of PLAYWRIGHT_TOPICS) {
    const bucket = result.find((g) => g.groupId === topic.groupId)
    if (bucket) {
      bucket.topics.push(topic)
    } else {
      result.push({ groupId: topic.groupId, topics: [topic] })
    }
  }
  return result
}

/** Slug + title only — safe to pass from server layouts to client nav. */
export function getTopicNavByGroup(): TopicNavGrouped {
  return getTopicsByGroup().map((g) => ({
    groupId: g.groupId,
    topics: g.topics.map((t) => ({ slug: t.slug, title: t.title })),
  }))
}
